package com.codex.evoxquickfix.debloat;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

final class DebloatEmergencyScript {
    static final String ROOT_PATH = "/data/adb/evox-quick-fix/debloat-restore.sh";

    private DebloatEmergencyScript() {}

    static String render(DebloatLedger ledger) {
        ledger.validate();
        List<DebloatLedger.Entry> restore = new ArrayList<>();
        for (DebloatLedger.Entry entry : ledger.entries.values()) {
            if (entry.managed || entry.pending) {
                restore.add(entry);
            }
        }
        restore.sort(Comparator.comparingLong((DebloatLedger.Entry item) -> item.sequence)
                .reversed());

        StringBuilder script = new StringBuilder(512);
        script.append("#!/system/bin/sh\n")
                .append("# Generated by EvoX Quick Fix. Restores only ledger-owned packages.\n")
                .append("umask 077\n")
                .append("status=0\n");
        for (DebloatLedger.Entry entry : restore) {
            script.append(entry.baselineState.exactRestoreCommand(entry.packageName))
                    .append(" || status=1\n");
        }
        return script.append("exit \"$status\"\n").toString();
    }
}
